name: splat-distiller
channels:
  - nvidia/label/cuda-12.8.0
  - nvidia
  - rapidsai-nightly
  - conda-forge
dependencies:
  - python=3.10
  - rapids=25.08
  - 'cuda-version>=12.8'
  - cuda-toolkit
  - compilers

