# config.yaml
hydra:
  run:
    # keep working dir where you launched the script
    dir: .

# Path to your LERF OVS root folder
lerf_ovs: "/media/bxiong/c6deb427-f841-4fb3-8707-2d0593655c63/lerf_ovs"

# Where to write all outputs
output_path: "/media/bxiong/c6deb427-f841-4fb3-8707-2d0593655c63/models/results_metrics_featup"

extension: None

# Which steps to skip
skip:
    feature_extraction: True
    training:        True
    lifting:         True
    evaluation:      false


# Feature extraction settings

feature_extraction:
    method: "maskclip" # one of [maskclip, SAMOpenCLIP]
    folder: "maskclip_features"
    sam_ckpt_path: 

# Training settings
training:
    splat_method: "3DGS"         # one of [3DGS, 2DGS, DBS]



# Distillation settings
distillation:
    quantize: False



# Evaluation settings
evaluation:
    rendering_mode: "RGB+AttentionMap+VIS"
    metrics: "attention_map"
